name: 'zervice.plex'

on:
  schedule:
    - cron:  '*/2 * * * *'
  push:
    branches: [master]

jobs:
  ping:
    runs-on: ${{ matrix.interface.runs-on }}
    timeout-minutes: 2
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        interface:
          - name: lan
            host: 192.168.1.41
            runs-on: [self-hosted, linux, hut]
          - name: vpn
            host: 100.77.217.17
            runs-on: [self-hosted, linux, vpn]
          - name: wan
            host: pumpkin.zalad.io
            runs-on: [ubuntu-latest]
          - name: argo
            host: plex.zervice.io
            runs-on: [ubuntu-latest]

    outputs:
      ping_pct_loss: ${{ steps.ping.outputs.ping_pct_loss }}
      ping_avg_rtt: ${{ steps.ping.outputs.ping_avg_rtt }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Ping check
        id: ping
        uses: ./.github/workflows/ping
        with:
          host: ${{ matrix.interface.host }}
          path: /github/workspace/ping_output.txt
        
      - name: Upload output
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ format('ping-{0}', matrix.interface.name) }}
          path: /github/workspace/ping_output.txt


  http:
    runs-on: ${{ matrix.interface.runs-on }}
    timeout-minutes: 2
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        interface:
          - name: lan
            scheme: http
            host: 192.168.1.41
            port: 32400
            path: /web/index.html
            runs-on: [self-hosted, linux, hut]
          - name: vpn
            scheme: http
            host: 100.77.217.17
            port: 32400
            path: /web/index.html
            runs-on: [self-hosted, linux, vpn]
          - name: wan
            scheme: http
            host: pumpkin.zalad.io
            port: 32400
            path: /web/index.html
            runs-on: [ubuntu-latest]
          - name: argo
            scheme: https
            host: plex.zervice.io
            port: 443
            path: /web/index.html
            runs-on: [ubuntu-latest]

    outputs:
      http_code: ${{ steps.http.outputs.http_code }}
      total_time: ${{ steps.http.outputs.total_time }}

    steps:
      - uses: actions/checkout@v2

      - name: HTTP check
        id: http
        uses: ./.github/workflows/http
        with:
          url: ${{ format('{0}://{1}:{2}{3}', matrix.interface.scheme, matrix.interface.host, matrix.interface.port, matrix.interface.path || '/') }}
          stats_path: /github/workspace/curl_stats.txt
          
      - name: Upload output
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ format('curl-{0}', matrix.interface.name) }}
          path: /github/workspace/curl_stats.txt
