name: 'zervice.plex'

on:
  schedule:
    - cron:  '*/2 * * * *'
  push:
    branches: [master]

jobs:
  ping:
    runs-on: ${{ matrix.interface.runs-on }}
    timeout-minutes: 2
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        interface:
          - name: lan
            host: 192.168.1.41
            runs-on: [self-hosted, linux, hut]
          - name: vpn
            host: 100.77.217.17
            runs-on: [self-hosted, linux, vpn]
          - name: wan
            host: pumpkin.zalad.io
            runs-on: [ubuntu-latest]
          - name: argo
            host: plex.zervice.io
            runs-on: [ubuntu-latest]

    env:
      PING_COUNT: 5
      PING_TIMEOUT: 5

    outputs:
      ping_pct_loss: ${{ steps.ping.outputs.ping_pct_loss }}
      ping_avg_rtt: ${{ steps.ping.outputs.ping_avg_rtt }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Ping check
        id: ping
        uses: ./.github/workflows/ping
        with:
          host: ${{ matrix.interface.host }}
          path: ping_output.txt

      - name: Get CPU usage
        id: sys_usage
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: COUNT,TIMEOUT,PATH
          script: |
            bash -c '
              ping \
                  -c "$PING_COUNT" \
                  -t "$PING_TIMEOUT" \
                  $INPUT_ARGS "$INPUT_HOST" > "$INPUT_PATH"

              OUTPUT="$(cat "$INPUT_PATH")"

              PCT_LOSS="$(cat "$INPUT_PATH" | tail -n 2 | grep 'packet loss' | perl -pe 's/^.* ([0-9\.]+). packet loss.*$/$1/')"
              echo "::set-output name=ping_pct_loss::$PCT_LOSS"

              AVG_RTT="$(cat "$INPUT_PATH" | tail -n 2 | grep 'round-trip' | awk -F'/' '{print $4}')"
              echo "::set-output name=ping_avg_rtt::$AVG_RTT"
            '

      - name: Upload output to server
        run: |
          cat ping_output.txt
        
      - name: Upload output to GitHub
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ format('ping-{0}', matrix.interface.name) }}
          path: ping_output.txt


  http:
    runs-on: ${{ matrix.interface.runs-on }}
    timeout-minutes: 2
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        interface:
          - name: lan
            scheme: http
            host: 192.168.1.41
            port: 32400
            path: /web/index.html
            runs-on: [self-hosted, linux, hut]
          - name: vpn
            scheme: http
            host: 100.77.217.17
            port: 32400
            path: /web/index.html
            runs-on: [self-hosted, linux, vpn]
          - name: wan
            scheme: http
            host: pumpkin.zalad.io
            port: 32400
            path: /web/index.html
            runs-on: [ubuntu-latest]
          - name: argo
            scheme: https
            host: plex.zervice.io
            port: 443
            path: /web/index.html
            runs-on: [ubuntu-latest]

    outputs:
      http_code: ${{ steps.http.outputs.http_code }}
      total_time: ${{ steps.http.outputs.total_time }}

    steps:
      - uses: actions/checkout@v2

      - name: HTTP check
        id: http
        uses: ./.github/workflows/http
        with:
          url: ${{ format('{0}://{1}:{2}{3}', matrix.interface.scheme, matrix.interface.host, matrix.interface.port, matrix.interface.path || '/') }}
          stats_path: curl_stats.txt

      - name: Upload output to server
        run: |
          cat curl_stats.txt
          
      - name: Upload output to GitHub
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ format('curl-{0}', matrix.interface.name) }}
          path: curl_stats.txt

  sys:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    continue-on-error: true

    outputs:
      cpu_usage: ${{ steps.sys_usage.outputs.cpu_usage }}
      ram_usage: ${{ steps.sys_usage.outputs.ram_usage }}
      swap_usage: ${{ steps.sys_usage.outputs.swap_usage }}
      disk_usage: ${{ steps.sys_usage.outputs.disk_usage }}

    steps:
      - uses: actions/checkout@v2

      - name: Get CPU usage
        id: sys_usage
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            bash -c '
            
            # CPU USage
            uptime \
            | sed \'s/.*: //\' \
            | sed \'s/, / /g\' \
            | awk -v CORES=$(nproc) \'{print ($1/CORES)*100}\' \
            | xargs -I {} -n 1 echo "::set-output name=cpu_usage::{}"
            
            # RAM Usage
            free -t \
            | awk \'FNR == 2 {print $3/$2*100}\' \
            | xargs -I {} -n 1 echo "::set-output name=ram_usage::{}"
            
            # Swap Usage
            free -t \
            | awk \'FNR == 3 {print $3/$2*100}\' \
            | xargs -I {} -n 1 echo "::set-output name=swap_usage::{}"
            
            # Disk Usage
            df -H / \
            | sort -nrk5 \
            | head -1 \
            | awk \'{print $5}\' \
            | tr -d % \
            | xargs -I {} -n 1 echo "::set-output name=disk_usage::{}"
            '
